version: "3.9"
services:

  api:
    build: 
      context: ./api
    environment:
      ConnectionStrings__FindABeer: "User ID=postgres;Password=mytestpassword;Host=database;Port=5432;Database=findabeer;Pooling=true;"
      DATABASE_NAME: findabeer
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: mytestpassword
      DATABASE_HOST: database
    # ports:
    #   - 5000:5000

  database:
    image: postgres
    environment:
      POSTGRES_DB: findabeer
      POSTGRES_PASSWORD: mytestpassword
    ports:
      - 5432:5432

  seeder:
    build:
      context: ./data
    environment:
      DATABASE_NAME: findabeer
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: mytestpassword
      DATABASE_HOST: database

  adminer:
    image: adminer
    ports:
      - 8080:8080
